---
title: "R Notebook"
output: html_notebook
---

# Libraries
```{r}

library(here)
library(dplyr)
library(tidyverse)
library(sf)
library(data.table)
library(ggplot2)
library(raster)
library(prismatic)
library(arulesCBA)
library(tibble)
library(osmdata)

```


# Import data

## observations
```{r}

filenames <- list.files(here("source"),pattern="*.gpkg$")

layers_s = c("09h30_staying","12h30_staying","15h30_staying","18h30_staying")
layers_m = c("09h30_moving","12h30_moving","15h30_moving","18h30_moving")

list_m = list()
list_s = list()

for (i in filenames) {

filename = i  
  
for (j in layers_s) {
df = st_read(here("source",filename),j)
df$fileid = filename
df$layer = j
df = df %>% dplyr::select(-Photo,-mode,-row,-id)
list_s[[length(list_s)+1]]=df
rm(df)
}

for (j in layers_m) {
df = st_read(here("source",filename),j)
df$fileid = paste0(filename,j)
df$fileid = filename
df$layer = j
df = df %>% dplyr::select(-Direction,-Photo)
list_m[[length(list_m)+1]]=df
rm(df)
}

rm(filename)

}

df_s = rbindlist(list_s,use.names = FALSE) %>% st_as_sf()
df_s %>% ggplot() + geom_sf()
df_m = rbindlist(list_m,use.names = FALSE) %>% st_as_sf()
df_m %>% ggplot() + geom_sf()

df_s = df_s %>% 
  rename_with(~ gsub(".", "_", .x, fixed = TRUE))

df_m = df_m %>% 
  rename_with(~ gsub(".", "_", .x, fixed = TRUE))

```

## context
```{r}

buildings <- read_sf(here("source","geom","context.gpkg"),"buildings")
plot(buildings)
boundary = read_sf(here("source","geom","context.gpkg"),"perimetre") %>% slice(1)
plot(boundary)
zones = read_sf(here("source","geom","context.gpkg"),"zones")
plot(zones)
track = read_sf(here("source","geom","track.gpkg"),"track3")
plot(track)

basemap = stack(here("source","geom","basemap.tif"))
basemap_df = as.data.frame(basemap, xy= TRUE)
basemap_df = 
  basemap_df %>% 
  rename(red = basemap_1, #Rename bands
         green = basemap_2,
         blue = basemap_3) %>%
  filter(red != 0) #drop data w/o rgb information

map = stack(here("source","geom","map_georeferenced_clip.tif"))
map_df = as.data.frame(map, xy= TRUE)
map_df = 
  map_df %>% 
  rename(red = map_georeferenced_clip_1, #Rename bands
         green = map_georeferenced_clip_2,
         blue = map_georeferenced_clip_3) %>%
  filter(red != 0) #drop data w/o rgb information

bbox <- st_bbox(st_buffer(boundary,dist = 5, joinStyle="ROUND")) #global



```

## openstreetmaps data
```{r}

# the bounding box, limiting what we fetch
#bbox_osm =
#  data.frame(min = c(bbox["xmin"],bbox["ymin"]),
#             max = c(bbox["xmax"],bbox["ymax"]))
#row.names(bbox_osm) = c("x","y")
#bbox_osm = as.matrix(bbox_osm)  

bbox_osm = getbb("nantes france", featuretype = "city")

# tree
map_tree <- bbox_osm %>% 
  opq() %>% 
  add_osm_feature(key = "natural", 
                  value = "tree") %>% 
  osmdata_sf()

# jardins
map_garden <- bbox_osm %>% 
  opq() %>% 
  add_osm_feature(key = "leisure", 
                  value = c("garden","park")) %>% 
  osmdata_sf()

# jardins
map_grass <- bbox_osm %>% 
  opq() %>% 
  add_osm_feature(key = "landuse", 
                  value = "grass") %>% 
  osmdata_sf()

# fontaines
map_eau <- bbox_osm %>% 
  opq() %>% 
  add_osm_feature(key = "natural", 
                  value = "water") %>% 
  osmdata_sf()

#tramway
map_tram <- bbox_osm %>% 
  opq() %>% 
  add_osm_feature(key = "electrified", 
                  value = "contact_line") %>% 
  osmdata_sf()

#platform
map_tram_platform <- bbox_osm %>% 
  opq() %>% 
  add_osm_feature(key = "public_transport", 
                  value = "platform") %>% 
  osmdata_sf()

#building civic
map_building_civic <- bbox_osm %>% 
  opq() %>% 
  add_osm_feature(key = "building", 
                  value = "civic") %>% 
  osmdata_sf()

bbox_4326 = st_bbox(st_transform(st_as_sfc(bbox), 4326))


ggplot() +
  geom_sf(data = map_garden$osm_polygons, fill = "#9DBF9E", col = "#9DBF9E") +
  geom_sf(data = map_grass$osm_polygons, fill = "#9DBF9E", col = "#9DBF9E") +
  geom_sf(data = map_tram$osm_lines, lwd = 1, colour = "gray") +
  geom_sf(data = map_tram_platform$osm_polygons, col = "gray") +
  geom_sf(data = map_tree$osm_points, size = 0.5, col = "#4A6C6F") +
  geom_sf(data = map_eau$osm_polygons, fill = "#9DDBFF", col = "#9DDBFF") +
  geom_sf(data = st_transform(buildings, 4326), col = "black", fill = "black") +
  geom_sf(data = map_building_civic$osm_polygons, col = "black", fill = "black") +
  xlim(bbox_4326[["xmin"]],bbox_4326[["xmax"]])+
  ylim(bbox_4326[["ymin"]],bbox_4326[["ymax"]])+
  theme_bw()
  
  

```




#Data organisation

## IDs
```{r}

#survey_id
df_s$survey_id =
  paste0(
  str_split_i(df_s$fileid,"_",1),"_",
  str_split_i(df_s$fileid,"_",2),"_",
  str_split_i(df_s$fileid,"_",4),"_",
  gsub("h","",str_split_i(df_s$layer,"_",1)),
  "00")

df_m$survey_id =
  paste0(
  str_split_i(df_m$fileid,"_",1),"_",
  str_split_i(df_m$fileid,"_",2),"_",
  str_split_i(df_m$fileid,"_",4),"_",
  gsub("h","",str_split_i(df_m$layer,"_",1)),
  "00")

#observer_id
df_s$observer =
  gsub(".gpkg","",str_split_i(df_s$fileid,"_",5))

df_m$observer =
  gsub(".gpkg","",str_split_i(df_m$fileid,"_",5))

# row_id
df_s$row_id <- paste(df_s$survey_id, ave(df_s$timestamp,df_s$survey_id, FUN = seq_along), sep="_")
df_m$row_id <- paste(df_m$survey_id, ave(df_m$timestamp,df_m$survey_id, FUN = seq_along), sep="_")

#tc
df_s$tc = gsub("h",":",str_split_i(df_s$layer,"_",1))
df_m$tc = gsub("h",":",str_split_i(df_m$layer,"_",1))

```

## Means & totals
```{r}

# Row_total
df_s$row_total = df_s$gender_male+df_s$gender_female

df_s$gender_unknown = 
  ifelse(
    df_s$row_total == 0,
    df_s$age_0_14+df_s$age_15_24+df_s$age_25_44+df_s$age_45_64+df_s$age_65_74+df_s$age_75p,
    df_s$gender_unknown
    )

df_s$row_total = 
  ifelse(
    df_s$row_total == 0,
    df_s$age_0_14+df_s$age_15_24+df_s$age_25_44+df_s$age_45_64+df_s$age_65_74+df_s$age_75p,
    df_s$row_total
    )

df_s = df_s %>% filter(row_total != 0)
df_s = df_s %>% drop_na(activity)
  
df_m$row_total <- df_m$gender_male+df_m$gender_female

df_m$gender_unknown = 
  ifelse(
    df_m$row_total == 0,
    df_m$age_0_14+df_m$age_15_24+df_m$age_25_44+df_m$age_45_64+df_m$age_65_74+df_m$age_75p,
    df_m$gender_unknown
    )

df_m$row_total = 
  ifelse(
    df_m$row_total == 0,
    df_m$age_0_14+df_m$age_15_24+df_m$age_25_44+df_m$age_45_64+df_m$age_65_74+df_m$age_75p,
    df_m$row_total
    )

df_m = df_m %>% filter(row_total != 0)
df_m = df_m %>% drop_na(mouvement)


# Mean age per group
df_s$age_mean <- round(((df_s$age_0_14*7)+(df_s$age_15_24*19.5)+(df_s$age_25_44*34.5)+
                                (df_s$age_45_64*54.5)+(df_s$age_65_74*69.5)+
                                (df_s$age_75p*80))/df_s$row_total,digits = 1)

df_m$age_mean <- round(((df_m$age_0_14*7)+(df_m$age_15_24*19.5)+(df_m$age_25_44*34.5)+
                                (df_m$age_45_64*54.5)+(df_m$age_65_74*69.5)+
                                (df_m$age_75p*80))/df_m$row_total,digits = 1)

```


## Separating columns of time & date from timestamp
```{r}

df_s$date = as.Date(as.POSIXct(as.numeric(df_s$timestamp)/1000, origin="1970-01-01"))
df_m$date = as.Date(as.POSIXct(as.numeric(df_m$timestamp)/1000, origin="1970-01-01"))

df_s$time =
  format(
    as.POSIXct(as.numeric(df_s$timestamp)/1000, origin="1970-01-01", tz = "Europe/Berlin"),
    format = "%H:%M:%S")

df_m$time =
  format(
    as.POSIXct(as.numeric(df_m$timestamp)/1000, origin="1970-01-01", tz = "Europe/Berlin"),
    format = "%H:%M:%S")

```


## Adding coordinates WGS84
```{r}

#conversion of points into spatial feature object 
df_s_lb93 <- st_as_sf(df_s, coords = c("X_lb93", "Y_lb93"), crs = 2154, agr = "constant", remove = FALSE)
  
#conversion of Lambert93 coordinates into pseudo mercator (WGS84, EPSg 3857) for kepler.gl
df_s_wgs84 <- st_transform(df_s_lb93, 4326)
  
#extracting X and Y coordinates from geometry
df_s_xy_wgs84 <- st_coordinates(df_s_wgs84)
  
#replacing longitude and latitude by X and Y respectively
df_s$X_wgs84 <- df_s_xy_wgs84[,1]
df_s$Y_wgs84 <- df_s_xy_wgs84[,2]

```

## Reorder dataframe
```{r}

df_s = df_s[,c(
  "survey_id","row_id",
  "timestamp","date","time","tc",
  "X_lb93","Y_lb93","X_wgs84","Y_wgs84",
  "row_total","gender_male","gender_female","gender_unknown",
  "age_mean","age_0_14", "age_15_24","age_25_44","age_45_64","age_65_74","age_75p",
  "posture","interaction","clothing","exposure","activity","stay_time",
  "observer","layer","fileid","geom")]

df_m = df_m[,c(
  "survey_id","row_id",
  "timestamp","date","time","tc",
  "row_total","gender_male","gender_female","gender_unknown",
  "age_mean","age_0_14", "age_15_24","age_25_44","age_45_64","age_65_74","age_75p",
  "interaction","clothing","exposure","mouvement",
  "observer","layer","fileid","geom")]

```


```{r}

df_s_4326 =  st_transform(df_s, 4326)
df_m_4326 =  st_transform(df_m, 4326)

```


# Spatial aggregation

## mesh
```{r}

grid = 
  st_make_grid(
    boundary,
    cellsize = 7,
    square = FALSE) %>% 
  st_sf() %>% 
  st_cast %>%
  mutate(
    id = 1:n())

grid = grid %>%
  mutate(
    int = st_intersects(grid,boundary, sparse = F)
    ) %>%
  filter(int == T) %>%
  dplyr::select(-int)
  
plot(grid)

```


## aggregation
```{r}
hexbin_s =
  st_join(
    grid,
    df_s %>% filter(row_total != 0),
    left = FALSE,
    join = st_intersects) %>%
  group_by(id,fileid) %>%
  summarise(
    n = n(),
    nbp = sum(row_total),
    gender_male = sum(gender_male),
    gender_female = sum(gender_female))

hexbin_m =
  st_join(
    grid,
    df_m %>% filter(row_total != 0),
    left = FALSE,
    join = st_intersects) %>%
  group_by(id,fileid) %>%
  summarise(
    n = n(),
    nbp = sum(row_total),
    gender_male = sum(gender_male),
    gender_female = sum(gender_female))

```


# Plot

```{r}

theme_carto <-
  theme_bw() +
  theme(
    #axis.line=element_blank(),
    axis.text.x=element_blank(),
    axis.text.y=element_blank(),
    axis.ticks=element_blank(),
    axis.title.x=element_blank(),
    axis.title.y=element_blank(),
    #legend.position="none",
    panel.background=element_blank(),
    #panel.border=element_blank(),
    panel.grid.major=element_blank(),
    panel.grid.minor=element_blank(),
    plot.background=element_blank()
    )

```


```{r}

bck =
  ggplot() +
    geom_sf(data = map_garden$osm_polygons, fill = "#9DBF9E", col = "#9DBF9E") +
    geom_sf(data = map_grass$osm_polygons, fill = "#9DBF9E", col = "#9DBF9E") +
    geom_sf(data = map_tram$osm_lines, lwd = 1, colour = "grey70") +
    geom_sf(data = map_tram_platform$osm_polygons, col = "grey70") +
    geom_sf(data = map_tree$osm_points, size = 0.5, col = "#4A6C6F") +
    geom_sf(data = map_eau$osm_polygons, fill = "#9DDBFF", col = "#9DDBFF") +
    geom_sf(data = map_building_civic$osm_polygons, col = "grey25", fill = "grey25") +
    geom_sf(data = st_transform(buildings, 4326), col = "grey25", fill = "grey25")
  
#  geom_raster(
#    data = basemap_df, aes(x = x, y =y), fill = rgb(r = basemap_df$red, g = basemap_df$green, b = basemap_df$blue, maxColorValue = 255),
#    show.legend = FALSE)+
#  geom_raster(
#    data = map_df, aes(x = x, y =y), fill = rgb(r = map_df$red, g = map_df$green, b = map_df$blue, maxColorValue = 255),
#    show.legend = FALSE)

m = st_transform(df_m, 4326)
z = st_transform(zones, 4326)
#m = st_intersection(m,z)
s = st_transform(df_s, 4326)
#s = st_intersection(s,z)
m_hb = st_transform(hexbin_m, 4326)
s_hb = st_transform(hexbin_s, 4326)
g_hb = st_transform(grid, 4326)


bck +
#ggplot()+
  geom_sf(data = m, lwd = 0.4, alpha = 0.1, col = "black")+
  geom_sf(data = s, size = 0.4,alpha = 0.5, col = "black")+
  #geom_sf(data = z, alpha = 1, color = "red",fill = NA, lty = 1, lwd = 0.3)+
  xlim(bbox_4326[["xmin"]],bbox_4326[["xmax"]])+
  ylim(bbox_4326[["ymin"]],bbox_4326[["ymax"]])+
  theme_carto

ggsave(here("outcomes","all.jpg"), width = 3000, height = 3000, units = "px", dpi = 300)

bck +
#ggplot()+  
  geom_sf(data=g_hb, color = gray(0.5),size = 0.1, fill = NA)+
  geom_sf(data=s_hb, aes(fill = nbp,alpha = nbp))+
  #geom_sf(data=df_m, alpha = 0.2, color = "blue")+
  xlim(bbox_4326[["xmin"]],bbox_4326[["xmax"]])+
  ylim(bbox_4326[["ymin"]],bbox_4326[["ymax"]])+
  theme_carto

ggsave(here("outcomes","hex_staying.jpg"))

bck +
#ggplot()+  
  geom_sf(data=g_hb, color = gray(0.5),size = 0.1, fill = NA)+
  geom_sf(data=m_hb, aes(fill = nbp, alpha = nbp))+
  #geom_sf(data=df_m, alpha = 0.2, color = "blue")+
  xlim(bbox_4326[["xmin"]],bbox_4326[["xmax"]])+
  ylim(bbox_4326[["ymin"]],bbox_4326[["ymax"]])+
  theme_carto

#ggsave(here("outcomes","hex_moving.jpg"))

```

